# Welcome to Jekyll!
#

# Site settings
title: the hyphen
description: |
  coming soon
owner: kimberly wang # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: contact@thehyphen.io
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://the-hyphen.github.io" # the base hostname & protocol for your site

#############
# HTML Head #
#############

lang: "en"
author: "kimberly wang"
keywords: "kimberly, wang, writer, asian, american, asian-american, culture, issues, social, lifestyle, women"
favicon: "/images/favicon.ico"


social:
  twitter: https://twitter.com/_thehyphen
  github: https://github.com/the-hyphen
  linkedin-square: https://linkedin.com/in/
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
